### ISSUE TITLE
Add a license to the project

### ISSUE THREAD

**Issue by ironcladlou** [ailispaw/xhyvectl#2]
Please assign a license to this codebase. Thanks!

**Comment by ailispaw** [comment]
@ironcladlou Thank you for asking.
I will add a license. Is MIT good for you?

**Comment by ailispaw** [comment]
Oh, dose your codebase mean every source code?

**Comment by ironcladlou** [comment]
I was referring just to the xhyvectl repo. I personally have no problem with MIT! Thanks for the response.
